- name: loops of ansible
  hosts: localhost
  tasks:
    - name: loop tasks
      ansible.builtin.debug:
        msg: "Fruit Names - {{ item }}"
      loop:
        - Apple
        - Banana
        - Orange
        - Kiwi
    - name: loop tasks
      ansible.builtin.debug:
        msg: "Fruit Names - {{ item.Name }}, Qty - {{ item.Quantity }}"
      loop:
        {Name: "Almond", Quantity: 20}
        {Name: "Mango", Quantity: 13}
        {Name: "Carrot", Quantity: 40}