- name: printing msg
  hosts: all
  tasks:
    - name: Storing info of module
      ansible.builtin.shell: uptime
      register: OUTPUT
    - name: printing output
      ansible.builtin.debug:
        msg: "{{ OUTPUT }}"

